### ISSUE TITLE
Not compatible with IDEA 2020.1

### ISSUE THREAD

**Issue by tanmatra** [sevdokimov/RegexUtil#8]
```
java.lang.NoSuchMethodError: 'java.awt.Color com.intellij.openapi.wm.impl.content.ToolWindowContentUi.getBackground()'
	at com.ess.regexutil.ideaplugin.RegexpToolWindowFactory.createToolWindowContent(RegexpToolWindowFactory.java:19)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:493)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:473)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:918)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:864)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:578)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:561)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1769)
	at com.intellij.openapi.wm.impl.StripeButton$1.actionPerformed(StripeButton.java:62)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:312)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:832)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by InfRandomness** [comment]
Having the same error as well on phpstorm.

**Comment by cognifloyd** [comment]
Same issue on PyCharm 2020.1

The Regex Tester tab is blank due to this error. So, the plugin is no longer usable. It's a very helpful plugin!

**Comment by cognifloyd** [comment]
This is the line:
https://github.com/sevdokimov/RegexUtil/blob/c9da90e92cc01560830514b4b2a5e6877cf621ad/IdeaPlugin/src/com/ess/regexutil/ideaplugin/RegexpToolWindowFactory.java#L19

`ToolWindowImpl.getContentUi()` has been deprecated since about January (idea/201.3803.32).
https://github.com/JetBrains/intellij-community/commit/fff4e7116972d842c90fde475d6215cfce55c235
I'm not sure what replaced it. I see something in the git log about lazy tool windows creation, maybe that has something to do with this?

I can't see where getBackground() was defined.

**Comment by InfRandomness** [comment]
I am gonna fork the plugin and attempt to correct the bug with the help of google and the jetbrains doc. I'll try to PR if I can successfully fix the bug.

**Comment by cognifloyd** [comment]
Ah ha. The commit I mentioned made it so that `ToolWindowContentUi` no longer extends `JPanel`.
https://github.com/JetBrains/intellij-community/commit/fff4e7116972d842c90fde475d6215cfce55c235#diff-83df661d79a49a57658c05db5590d05aR48
`javax.swing.JPanel` extends `javax.swing.JComponent` extends `java.awt.Container` extends `java.awt.Component` which [implements](https://docs.oracle.com/javase/7/docs/api/java/awt/Component.html#getBackground()) `getBackground()`.

So, that was the commit that broke this.

**Comment by cognifloyd** [comment]
So, if there is a way to get the `ToolWindowContentUi`, then you need to use `(TabPanel) contentUi.getTabComponent().getBackground()` (where `TabPanel` is a private class that extends `JPanel` consolidating the UI rendering logic from ToolWindowContentUi).

We can get the `contentManager` with `toolWindow.getContentManager()` but that doesn't provide a way to get the `contentUi`.

What if we got the color somewhere else? `toolWindow.getComponent().getBackground()` or maybe `toolWindow.getComponent().getParent().getBackground()`?

**Comment by sevdokimov** [comment]
Fixed
